### ISSUE TITLE
Plugin is broken in Craft 3.7.17+

### ISSUE THREAD

**Issue by seandelaney** [experience/overflow.craft-plugin#5]
I originally reported the issue here: https://github.com/craftcms/cms/issues/10044 and it has been patched but probably best to update the plugin too. :)

**Comment by joelbradbury** [comment]
Bump

**Comment by monooso** [comment]
Hi @seandelaney, thanks for the bug report.

It's very unlikely I'm ever going to fix this. I don't currently have PHP installed, never mind Craft, and it's been a long time since I've done any Craft development.

At this point it's best to treat this plugin as retired, along with all of my other Craft plugins. You are, of course, free to fork any of them for your own purposes.
